### ISSUE TITLE
Roll-out new changes

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-bot#15]
I just added a new route `/comment/recreate` to keep the comments from the TLDR bot in a PR limited (by deleting a previous comment, which is outdated, and adding a new one at the end).

How can we make sure that new route is available at https://tldr-bot.starbeamrainbowlabs.com?

**Comment by sebastiaanspeck** [comment]
@sbrl you can use this issue to keep us updated about rolling out the latest tldr-bot changes on the VPS.

**Comment by sbrl** [comment]
Heya!

Ref  tldr-pages/tldr#13775 this rollout is now complete.

In future please do @mention me on Matrix to get my attention if I'm not responsive enough here on GH.
