### ISSUE TITLE
Change icon/profile pic of the tldr-bot

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-bot#4]
This was suggested in https://github.com/tldr-pages/tldr/pull/1199#issuecomment-267308669 and https://github.com/tldr-pages/tldr/pull/1380#issuecomment-302461706.

Here's a rough draft to get some ideas rolling:

<img width="300" alt="tldr-bot logo" src="https://cloud.githubusercontent.com/assets/478237/26215130/0a382f2c-3bf7-11e7-8ea1-9420d7a08c8c.png">

It is based on the current [tldr-pages project](https://github.com/tldr-pages) icon: 

![tldr-pages](https://cloud.githubusercontent.com/assets/478237/26215248/8b81089c-3bf7-11e7-92e1-b567ba595ad0.png)

**Comment by waldyrious** [comment]
For future reference, here's what the robot currently looks like:

<img src="https://avatars0.githubusercontent.com/u/23114548?v=3&s=400"/>

**Comment by agnivade** [comment]
This is done now.

**Comment by waldyrious** [comment]
x-ref: #8
