### ISSUE TITLE
Get tldr-bot marked as a bot account?

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr-bot#5]
The probot-stale bot we have running has a special `bot` tag next to it's name. Could we do this for @tldr-bot too?

**Comment by agnivade** [comment]
Yea I saw that, probot-stale is actually an integration. Not an account per-se. And this article mentions its fine to give an user account for bot purposes - https://help.github.com/articles/differences-between-user-and-organization-accounts/#personal-user-accounts
